"use client";
import Link from "next/link";
import {useEffect,useRef} from "react";
import {ChevronUp,Gauge,Maximize2,Music,Pause,Play,Repeat,RotateCcw,RotateCw,Shuffle,SkipBack,SkipForward,Volume2} from "lucide-react";
import {usePlayerStore} from "@/store/playerStore";
import {getProgress,queueProgress,saveProgress,syncPendingProgress} from "@/services/playbackService";
const fmt=(s:number)=>`${String(Math.floor((s||0)/60)).padStart(2,'0')}:${String(Math.floor((s||0)%60)).padStart(2,'0')}`;
const localKey=(storyId:string)=>`echotale-progress-${storyId}`;
export function BottomPlayer(){const audioRef=useRef<HTMLAudioElement|null>(null),lastSaved=useRef(0);const store=usePlayerStore();const{track,queue,isPlaying,isRepeat,isShuffle,currentTime,duration,playbackRate,volume,sleepTimerEnd,seekRequest}=store;
 function progressValue(){return track?{story_id:track.storyId,chapter_id:track.chapterId||'',current_time:currentTime,duration,percentage:duration?currentTime/duration*100:0,completed:duration>0&&currentTime/duration>=.98}:null}
 function persist(remote=true){const value=progressValue();if(!value)return;localStorage.setItem(localKey(value.story_id),JSON.stringify(value));if(remote){if(navigator.onLine)saveProgress(value).catch(()=>queueProgress(value));else queueProgress(value)}}
 useEffect(()=>{const online=()=>syncPendingProgress().catch(()=>{});addEventListener('online',online);online();return()=>removeEventListener('online',online)},[]);
 useEffect(()=>{const audio=audioRef.current;if(!audio||!track?.audioUrl)return;let cancelled=false;persist();audio.src=track.audioUrl;audio.load();store.setTiming(0,track.duration||0);const local=JSON.parse(localStorage.getItem(localKey(track.storyId))||'null');const restore=(p:any)=>{if(cancelled||!p||p.chapter_id!==(track.chapterId||''))return;const value=Math.max(0,Number(p.current_time)||0);audio.currentTime=value;store.setTiming(value,Number(p.duration)||track.duration||0)};restore(local);getProgress(track.storyId).then(restore).catch(()=>{});return()=>{cancelled=true}},[track?.audioUrl]);
 useEffect(()=>{const audio=audioRef.current;if(!audio||!track?.audioUrl)return;if(isPlaying)audio.play().catch(()=>store.setPlaying(false));else audio.pause()},[isPlaying,track?.audioUrl]);
 useEffect(()=>{if(audioRef.current){audioRef.current.playbackRate=playbackRate;audioRef.current.volume=volume}},[playbackRate,volume]);
 useEffect(()=>{if(audioRef.current&&seekRequest){audioRef.current.currentTime=Math.max(0,Math.min(seekRequest.value,audioRef.current.duration||duration));store.setTiming(audioRef.current.currentTime,duration)}},[seekRequest?.id]);
 useEffect(()=>{if(!sleepTimerEnd)return;const timer=setInterval(()=>{if(Date.now()>=sleepTimerEnd){store.setPlaying(false);store.setSleepTimer(null)}},1000);return()=>clearInterval(timer)},[sleepTimerEnd]);
 useEffect(()=>{if(!track||!('mediaSession'in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:track.author,album:'EchoTale',artwork:track.cover?[{src:track.cover,sizes:'512x512'}]:[]});const handlers:any={play:()=>store.setPlaying(true),pause:()=>store.setPlaying(false),seekbackward:()=>store.requestSeek(Math.max(0,usePlayerStore.getState().currentTime-10)),seekforward:()=>store.requestSeek(usePlayerStore.getState().currentTime+10),previoustrack:store.playPrevious,nexttrack:store.playNext,seekto:(d:any)=>d.seekTime!=null&&store.requestSeek(d.seekTime)};Object.entries(handlers).forEach(([a,h])=>{try{navigator.mediaSession.setActionHandler(a as MediaSessionAction,h as any)}catch{}})},[track?.id]);
 useEffect(()=>{if(!('mediaSession'in navigator)||!duration||duration===Infinity)return;try{navigator.mediaSession.playbackState=isPlaying?'playing':'paused';navigator.mediaSession.setPositionState({duration:Math.max(duration,.1),playbackRate,position:Math.min(currentTime,duration)})}catch{}},[currentTime,duration,isPlaying,playbackRate]);
 if(!track)return null;const update=()=>{const a=audioRef.current;if(!a)return;store.setTiming(a.currentTime,a.duration||track.duration||0);if(a.currentTime-lastSaved.current>=15){lastSaved.current=a.currentTime;persist()}};const ended=()=>{persist();if(isRepeat){store.requestSeek(0);store.setPlaying(true)}else if(queue.length>1)store.playNext();else store.setPlaying(false)};const seek=(delta:number)=>store.requestSeek(currentTime+delta);
 return <><audio ref={audioRef} onTimeUpdate={update} onLoadedMetadata={()=>{const a=audioRef.current;if(a)store.setTiming(a.currentTime,a.duration||track.duration||0)}} onPause={()=>persist()} onEnded={ended} preload="metadata"/>
 <div className="fixed bottom-[68px] left-3 right-3 z-40 flex items-center gap-3 rounded-2xl border border-borderSoft bg-white/95 p-2 shadow-card backdrop-blur lg:hidden">{track.cover?<img src={track.cover} alt="" className="h-11 w-11 rounded-xl object-cover"/>:<span className="grid h-11 w-11 place-items-center rounded-xl bg-soft"><Music size={18}/></span>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold">{track.title}</p><div className="mt-1 h-1 overflow-hidden rounded-full bg-soft"><div className="h-full bg-primary" style={{width:`${duration?currentTime/duration*100:0}%`}}/></div></div><button onClick={()=>seek(-10)}><RotateCcw size={18}/></button><button onClick={store.togglePlay} className="grid h-9 w-9 place-items-center rounded-full bg-primary text-white">{isPlaying?<Pause size={17}/>:<Play size={17}/>}</button><Link href="/player"><ChevronUp size={19}/></Link></div>
 <div className="fixed bottom-0 left-0 right-0 z-30 hidden h-[92px] items-center justify-between border-t border-borderSoft bg-white/95 px-7 shadow-card backdrop-blur lg:flex"><div className="flex w-64 items-center gap-3">{track.cover?<img src={track.cover} alt="" className="h-14 w-14 rounded-xl object-cover"/>:<span className="grid h-14 w-14 place-items-center rounded-xl bg-soft"><Music/></span>}<div className="min-w-0"><p className="truncate text-sm font-extrabold">{track.title}</p><p className="truncate text-xs text-textMuted">{track.author}</p></div></div>
 <div className="flex items-center gap-4"><button onClick={store.toggleShuffle} className={isShuffle?'text-primary':''}><Shuffle size={17}/></button><button onClick={store.playPrevious}><SkipBack size={20}/></button><button title="Back 10 seconds" onClick={()=>seek(-10)}><RotateCcw size={19}/></button><button onClick={store.togglePlay} className="grid h-12 w-12 place-items-center rounded-full bg-primary text-white">{isPlaying?<Pause/>:<Play/>}</button><button title="Forward 10 seconds" onClick={()=>seek(10)}><RotateCw size={19}/></button><button onClick={store.playNext}><SkipForward size={20}/></button><button onClick={store.toggleRepeat} className={isRepeat?'text-primary':''}><Repeat size={17}/></button></div>
 <div className="flex w-[430px] items-center gap-3"><span className="w-[86px] text-[11px] text-textMuted">{fmt(currentTime)} / {fmt(duration)}</span><input aria-label="Playback progress" type="range" min={0} max={duration||0} value={Math.min(currentTime,duration||0)} onChange={e=>store.requestSeek(Number(e.target.value))} className="min-w-0 flex-1 accent-primary"/><Gauge size={16}/><select aria-label="Playback speed" value={playbackRate} onChange={e=>store.setPlaybackRate(Number(e.target.value))} className="rounded-lg border border-borderSoft bg-white px-2 py-1 text-xs font-bold">{[.5,.75,1,1.25,1.5,1.75,2].map(v=><option key={v} value={v}>{v}×</option>)}</select><Volume2 size={16}/><input aria-label="Volume" type="range" min={0} max={1} step={0.05} value={volume} onChange={e=>store.setVolume(Number(e.target.value))} className="w-14 accent-primary"/><Link href="/player" title="Full-screen player"><Maximize2 size={18}/></Link></div></div></>}

