import type {Story} from "@/services/storyService";
import {getMediaUrl} from "@/services/storyService";
import {removeDownloadRecord,syncDownload} from "@/services/playbackService";
const CACHE='echotale-downloads-v1',KEY='echotale-offline-library';
export type OfflineBook={storyId:string;title:string;author:string;cover:string;urls:string[];chapterIds:string[];bytes:number;downloadedAt:string};
export function getOfflineBooks():OfflineBook[]{if(typeof window==='undefined')return[];try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(items:OfflineBook[]){localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new Event('echotale-downloads-changed'))}
async function cacheUrl(cache:Cache,url:string,onBytes:(n:number,total:number)=>void){const response=await fetch(url);if(!response.ok)throw new Error(`Download failed: ${response.status}`);const total=Number(response.headers.get('content-length')||0);if(!response.body){await cache.put(url,response.clone());onBytes(total,total);return total}const reader=response.body.getReader();const chunks:Uint8Array[]=[];let received=0;while(true){const{done,value}=await reader.read();if(done)break;if(value){chunks.push(value);received+=value.length;onBytes(received,total)}}const blob=new Blob(chunks.map((chunk) => chunk.slice().buffer as ArrayBuffer),{type:response.headers.get('content-type')||'application/octet-stream'});await cache.put(url,new Response(blob,{headers:{'Content-Type':blob.type,'Content-Length':String(blob.size)}}));return blob.size}
export async function downloadStory(story:Story,onProgress:(value:number)=>void){if(!('caches'in window))throw new Error('Offline downloads are not supported in this browser.');const parts=(story.audio_parts||[]).filter(p=>p.audio_url);const urls=[getMediaUrl(story.cover_image),...parts.map(p=>getMediaUrl(p.audio_url))].filter(Boolean);if(!parts.length&&story.audio_url)urls.push(getMediaUrl(story.audio_url));if(!urls.length)throw new Error('No downloadable audio is available.');const cache=await caches.open(CACHE);let bytes=0;for(let i=0;i<urls.length;i++){bytes+=await cacheUrl(cache,urls[i],(received,total)=>{const fraction=total?received/total:0.6;onProgress(Math.round(((i+fraction)/urls.length)*100))})}const item:OfflineBook={storyId:story.id,title:story.title,author:story.author,cover:getMediaUrl(story.cover_image),urls,chapterIds:parts.map(p=>String(p.part_number)),bytes,downloadedAt:new Date().toISOString()};save([...getOfflineBooks().filter(i=>i.storyId!==story.id),item]);onProgress(100);try{await syncDownload({story_id:story.id,chapter_ids:item.chapterIds,total_bytes:bytes})}catch{}return item}
export async function removeOfflineStory(storyId:string){const item=getOfflineBooks().find(i=>i.storyId===storyId);if(item){const cache=await caches.open(CACHE);await Promise.all(item.urls.map(url=>cache.delete(url)))}save(getOfflineBooks().filter(i=>i.storyId!==storyId));try{await removeDownloadRecord(storyId)}catch{}}
export function isStoryOffline(id:string){return getOfflineBooks().some(i=>i.storyId===id)}
export async function storageEstimate(){const estimate=await navigator.storage?.estimate?.();return{usage:estimate?.usage||getOfflineBooks().reduce((n,i)=>n+i.bytes,0),quota:estimate?.quota||0}}


export async function syncOfflineLibrary(){for(const item of getOfflineBooks()){await syncDownload({story_id:item.storyId,chapter_ids:item.chapterIds,total_bytes:item.bytes})}}

