"use client";
import {create} from "zustand";
export type PlayerTrack={id:string;storyId:string;chapterId?:string;chapterNumber?:number;title:string;author:string;cover:string;duration:number;audioUrl?:string;textPreview?:string};
type SeekRequest={value:number;id:number}|null;
type PlayerState={track:PlayerTrack|null;queue:PlayerTrack[];currentIndex:number;isPlaying:boolean;isExpanded:boolean;isRepeat:boolean;isShuffle:boolean;currentTime:number;duration:number;playbackRate:number;volume:number;sleepTimerEnd:number|null;seekRequest:SeekRequest;setTrack:(t:PlayerTrack)=>void;setQueue:(q:PlayerTrack[],i?:number)=>void;clearTrack:()=>void;togglePlay:()=>void;setPlaying:(v:boolean)=>void;playNext:()=>void;playPrevious:()=>void;toggleExpanded:()=>void;toggleRepeat:()=>void;toggleShuffle:()=>void;setTiming:(t:number,d:number)=>void;requestSeek:(v:number)=>void;setPlaybackRate:(v:number)=>void;setVolume:(v:number)=>void;setSleepTimer:(minutes:number|null)=>void};
export const usePlayerStore=create<PlayerState>((set,get)=>({track:null,queue:[],currentIndex:-1,isPlaying:false,isExpanded:false,isRepeat:false,isShuffle:false,currentTime:0,duration:0,playbackRate:1,volume:1,sleepTimerEnd:null,seekRequest:null,
 setTrack:t=>set({track:t,queue:[t],currentIndex:0,isPlaying:true,currentTime:0,duration:t.duration||0}),
 setQueue:(q,i=0)=>{const safe=Math.max(0,Math.min(i,q.length-1)),track=q[safe]||null;set({queue:q,currentIndex:track?safe:-1,track,isPlaying:!!track,currentTime:0,duration:track?.duration||0})},
 clearTrack:()=>set({track:null,queue:[],currentIndex:-1,isPlaying:false,currentTime:0,duration:0}),togglePlay:()=>set(s=>({isPlaying:!s.isPlaying})),setPlaying:v=>set({isPlaying:v}),
 playNext:()=>{const{queue,currentIndex,isShuffle}=get();if(!queue.length)return;let i=currentIndex+1;if(isShuffle&&queue.length>1){i=Math.floor(Math.random()*queue.length);if(i===currentIndex)i=(i+1)%queue.length}if(i>=queue.length)i=0;set({currentIndex:i,track:queue[i],isPlaying:true,currentTime:0,duration:queue[i].duration||0})},
 playPrevious:()=>{const{queue,currentIndex}=get();if(!queue.length)return;const i=currentIndex<=0?queue.length-1:currentIndex-1;set({currentIndex:i,track:queue[i],isPlaying:true,currentTime:0,duration:queue[i].duration||0})},toggleExpanded:()=>set(s=>({isExpanded:!s.isExpanded})),toggleRepeat:()=>set(s=>({isRepeat:!s.isRepeat})),toggleShuffle:()=>set(s=>({isShuffle:!s.isShuffle})),setTiming:(currentTime,duration)=>set({currentTime,duration}),requestSeek:value=>set({seekRequest:{value,id:Date.now()}}),setPlaybackRate:playbackRate=>set({playbackRate}),setVolume:volume=>set({volume}),setSleepTimer:minutes=>set({sleepTimerEnd:minutes?Date.now()+minutes*60000:null})}));
