"use client";
import Link from "next/link";
import { useEffect,useMemo,useRef,useState } from "react";
import { BookOpen,Database,ExternalLink,FileText,Library,Loader2,Search,X } from "lucide-react";
import { getStories,type Story } from "@/services/storyService";
import { searchOpenLibrary,type LibraryBook } from "@/services/libraryService";
export function HeaderBookSearch(){
 const root=useRef<HTMLDivElement>(null);const [query,setQuery]=useState("");const [stories,setStories]=useState<Story[]>([]);const [books,setBooks]=useState<LibraryBook[]>([]);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [warning,setWarning]=useState("");
 useEffect(()=>{getStories().then(setStories).catch(()=>setStories([]));const outside=(e:MouseEvent)=>{if(root.current&&!root.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",outside);return()=>document.removeEventListener("mousedown",outside)},[]);
 const local=useMemo(()=>{const q=query.trim().toLowerCase();return q.length<2?[]:stories.filter(s=>[s.title,s.author,s.category,s.description].some(v=>v?.toLowerCase().includes(q))).slice(0,4)},[query,stories]);
 useEffect(()=>{const clean=query.trim();if(clean.length<2){setBooks([]);setLoading(false);return}setOpen(true);setLoading(true);setWarning("");const controller=new AbortController();const timer=setTimeout(()=>searchOpenLibrary(clean,controller.signal).then(data=>{setBooks(data.books.slice(0,6));setWarning(data.warning||"")}).catch(error=>{if(error.name!=="AbortError")setWarning("Free library results are temporarily unavailable.")}).finally(()=>setLoading(false)),450);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 function submit(e:React.FormEvent){e.preventDefault();if(query.trim().length>=2)setOpen(true)}
 const hasResults=local.length>0||books.length>0;
 return <div ref={root} className="relative w-full max-w-[700px]"><form onSubmit={submit} className="flex h-12 items-center gap-3 rounded-2xl border border-[#e8e6ef] bg-white/95 px-4 shadow-[0_6px_24px_rgba(31,25,61,.05)] transition focus-within:border-primary/40 focus-within:ring-4 focus-within:ring-primary/10 sm:h-14 sm:px-5"><Search className="shrink-0 text-[#6E6A7C]" size={23}/><input value={query} onFocus={()=>query.trim().length>=2&&setOpen(true)} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Escape")setOpen(false)}} placeholder="Search any book, author, or topic..." className="w-full bg-transparent text-base outline-none placeholder:text-[#98A2B3]"/>{loading&&<Loader2 size={18} className="shrink-0 animate-spin text-primary"/>}{query&&<button type="button" onClick={()=>{setQuery("");setOpen(false)}} aria-label="Clear search" className="grid h-7 w-7 shrink-0 place-items-center rounded-lg text-textMuted hover:bg-soft"><X size={16}/></button>}</form>
 {open&&<div className="absolute left-0 top-[calc(100%+10px)] z-[80] w-[min(860px,calc(100vw-32px))] overflow-hidden rounded-[22px] border border-[#e8e3ee] bg-white shadow-[0_25px_70px_rgba(23,17,47,.2)]"><div className="flex items-center justify-between border-b border-borderSoft bg-[#faf8fc] px-5 py-3"><div><p className="text-sm font-extrabold text-textMain">Book search</p><p className="text-[11px] text-textMuted">EchoTale library + Open Library</p></div><span className="rounded-full bg-soft px-2.5 py-1 text-[10px] font-bold text-primary">Results update as you type</span></div><div className="max-h-[520px] overflow-y-auto p-4">
 {query.trim().length<2?<Empty text="Type at least 2 characters to search."/>:!loading&&!hasResults?<Empty text={`No books found for “${query}”.`}/>:<div className="space-y-5">{local.length>0&&<section><Label icon={<Database size={14}/>} title="In EchoTale"/><div className="mt-2 grid gap-2 sm:grid-cols-2">{local.map(s=><Link key={s.id} href={`/stories/${s.id}`} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl border border-borderSoft p-2.5 hover:border-primary/25 hover:bg-soft/50"><div className="grid h-12 w-10 shrink-0 place-items-center overflow-hidden rounded-lg bg-soft">{s.cover_image?<img src={s.cover_image.startsWith("http")?s.cover_image:`http://127.0.0.1:8000${s.cover_image}`} alt="" className="h-full w-full object-cover"/>:<BookOpen size={17} className="text-primary"/>}</div><div className="min-w-0"><p className="truncate text-xs font-extrabold">{s.title}</p><p className="truncate text-[11px] text-textMuted">{s.author}</p></div></Link>)}</div></section>}
 <section><Label icon={<Library size={14}/>} title="From Open Library"/>{warning&&<p className="mt-2 text-xs text-amber-700">{warning}</p>}{loading&&books.length===0?<div className="grid h-24 place-items-center"><Loader2 className="animate-spin text-primary" size={23}/></div>:<div className="mt-2 grid gap-2 sm:grid-cols-2">{books.map(b=><ExternalResult key={b.id} book={b}/>)}</div>}</section></div>}
 </div><div className="border-t border-borderSoft bg-[#faf8fc] px-5 py-3 text-[10px] text-textMuted">Free Read and PDF buttons appear only for publicly accessible scans. External links open in a new tab.</div></div>}</div>
}
function Label({icon,title}:{icon:React.ReactNode;title:string}){return <h3 className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.1em] text-textMuted">{icon}{title}</h3>}
function Empty({text}:{text:string}){return <div className="grid min-h-28 place-items-center text-sm text-textMuted">{text}</div>}
function ExternalResult({book}:{book:LibraryBook}){return <article className="flex gap-3 rounded-xl border border-borderSoft p-2.5 transition hover:border-primary/25"><div className="grid h-[76px] w-[54px] shrink-0 place-items-center overflow-hidden rounded-lg bg-soft">{book.coverUrl?<img src={book.coverUrl} alt="" className="h-full w-full object-cover"/>:<BookOpen size={19} className="text-primary"/>}</div><div className="min-w-0 flex-1"><p className="line-clamp-1 text-xs font-extrabold">{book.title}</p><p className="mt-0.5 truncate text-[10px] text-textMuted">{book.author}{book.year?` · ${book.year}`:""}</p><div className="mt-2 flex flex-wrap gap-1.5"><a href={book.detailsUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md bg-[#17112f] px-2 py-1 text-[9px] font-bold text-white">Details<ExternalLink size={9}/></a>{book.freeToRead&&<a href={book.readUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-[9px] font-bold text-white">Read<BookOpen size={9}/></a>}{book.pdfUrl&&<a href={book.pdfUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md bg-soft px-2 py-1 text-[9px] font-bold text-primary">PDF<FileText size={9}/></a>}</div></div></article>}
