"use client";
import { BookOpen, ExternalLink, FileText, Library, Languages } from "lucide-react";
import type { LibraryBook } from "@/services/libraryService";
export function LibraryBookCard({book}:{book:LibraryBook}){
  return <article className="group flex min-w-0 overflow-hidden rounded-[20px] border border-borderSoft bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-[0_16px_38px_rgba(31,23,61,.1)]">
    <div className="w-[112px] shrink-0 bg-gradient-to-br from-soft to-[#e8e1f1] sm:w-[132px]">{book.coverUrl?<img src={book.coverUrl} alt={`Cover of ${book.title}`} className="h-full min-h-[190px] w-full object-cover" onError={(e)=>{e.currentTarget.style.display="none"}}/>:<div className="grid h-full min-h-[190px] place-items-center"><BookOpen size={32} className="text-primary/50"/></div>}</div>
    <div className="flex min-w-0 flex-1 flex-col p-4"><div className="flex items-start justify-between gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#f2edff] px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-primary"><Library size={11}/> Open Library</span>{book.freeToRead&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Free full text</span>}</div><h3 className="mt-3 line-clamp-2 text-base font-extrabold leading-5 text-textMain">{book.title}</h3><p className="mt-1 line-clamp-1 text-xs font-semibold text-textMuted">{book.author}</p><div className="mt-3 flex flex-wrap gap-2 text-[10px] font-semibold text-textMuted">{book.year&&<span>{book.year}</span>}<span>{book.editionCount} editions</span>{book.language&&<span className="inline-flex items-center gap-1"><Languages size={11}/>{book.language.toUpperCase()}</span>}</div><p className="mt-2 line-clamp-1 text-[11px] text-textMuted">{book.subjects.slice(0,2).join(" · ")||"Book details and editions"}</p><div className="mt-auto flex flex-wrap gap-2 pt-4"><a href={book.detailsUrl} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-[#17112f] px-3 text-[11px] font-bold text-white">Details <ExternalLink size={12}/></a>{book.freeToRead&&<a href={book.readUrl} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-primary px-3 text-[11px] font-bold text-white"><BookOpen size={12}/>Read free</a>}{book.pdfUrl&&<a href={book.pdfUrl} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-primary/20 bg-soft px-3 text-[11px] font-bold text-primary"><FileText size={12}/>PDF</a>}</div></div>
  </article>;
}
